### ISSUE TITLE
Tab close button is bugged

### ISSUE THREAD

**Issue by Kooldude93** [sapierens/firefox-edge#1]
The tab close button seems to not be functioning correctly. I think it's the hover animation. I tried it without any other addons but that did not solve the issue. Here is a [picture](http://i.imgur.com/MoeWRQe.png) of it.

**Comment by HammyHavoc** [comment]
I noticed that too. Using the dark version.

**Comment by sapierens** [comment]
I assume it's because you have a high-dpi monitor. Is tab close button the only button that's affected?

**Comment by HammyHavoc** [comment]
I had a close button in the URL bar as well. If it's any additional help, I'm using Mozilla Test Pilot's Universal Search.

**Comment by HammyHavoc** [comment]
Here's a screenshot of another broken element, circled for emphasis.
<img width="960" alt="ff bug" src="https://cloud.githubusercontent.com/assets/503951/20762353/f9c70b8a-b71d-11e6-9e4c-89578a5c5f3b.PNG">

**Comment by Kooldude93** [comment]
Yeah I'm also getting the double icon that HammyHavoc posted.

**Comment by monjo44** [comment]
I had the same issue but after a restart it seams to work
