### ISSUE TITLE
Too big

### ISSUE THREAD

**Issue by amfakh** [sapierens/firefox-edge#15]
I think this picture is already representing what I mean, it's still too big for my usual 768p screen. Make it thinner or atleast make option to do it.

http://prnt.sc/dx8qte

**Comment by sapierens** [comment]
The current size replicates Microsoft Edge and adding an option to make it thinner would require too much change. Possibly including redoing all the images for smaller sizes, as the current ones would look blurry when slightly sized down.
I don't see myself doing this in the foreseeable future.
