### ISSUE TITLE
Some menu icons are invisible

### ISSUE THREAD

**Issue by alyms108** [sapierens/firefox-edge#16]
I think this problem occurred after Firefox updated to 51.0.1. I'm using Linux Mint 17.1. This is what the menu looks like when I have Firefox Edge disabled:
![menu-with-edge-disabled](https://cloud.githubusercontent.com/assets/10800186/22400878/a51c2eca-e586-11e6-8cc3-2381f18eb4b8.png)

This is what the menu looks like with the skin enabled:
![menu-with-edge-enabled](https://cloud.githubusercontent.com/assets/10800186/22400884/b7babc2c-e586-11e6-8f0f-298887ac0f00.png)

**Comment by sapierens** [comment]
This is already fixed in the update I just released.
