### ISSUE TITLE
request: pale moon browser port

### ISSUE THREAD

**Issue by Maggew** [sapierens/firefox-edge#17]
Excellent contribution! I thought if maybe I installed the [Australium Theme](https://addons.palemoon.org/themes/), your stylish script would look perfect.

Would you consider doing a port for Pale Moon?

http://www.palemoon.org/

**Comment by Lootyhoof** [comment]
FYI, although visually Australium looks as close as possible to default Firefox, under the hood it's quite different. To create a version of this for Pale Moon would likely involve re-writing a lot of things.

I'd be quite happy if this happened, but I figured I should let people know before any work goes into this to then realise things are different between the two browsers. Feel free to let me know if any help is required should someone work on this, of course.

**Comment by Maggew** [comment]
I reckon the amount of time required might not be rewarding enough. Thanks for swift reply and good luck Lootyhoof
