### ISSUE TITLE
v1.9.0 breaks corner usability of new tab button.

### ISSUE THREAD

**Issue by Claymont** [sapierens/firefox-edge#18]
v1.9.0 breaks usability of new tab button when placed far left on the tab bar when window is maximized. Left edge (including corner) of new tab button becomes unclickable.

`.tabs-newtab-button,#TabsToolbar #new-tab-button {
padding-right:0!important;
margin-left:1px!important
}` 

Changing `margin-left:1px!important` in the above code to `margin-left:0px!important` fixes it for me.

**Comment by sapierens** [comment]
Thanks! I didn't consider the fact that it's possible to place the new-tab button on the left side.
