### ISSUE TITLE
UI Icons look a little low-res

### ISSUE THREAD

**Issue by HammyHavoc** [sapierens/firefox-edge#2]
Love this, but the UI icons look a little fuzzy.

**Comment by sapierens** [comment]
Definitely another high-dpi issue. I have to recreate all images with double the size and add them to the theme, but userstyles' file size restriction doesn't permit me to add much more. I'll try to figure it out.

**Comment by HammyHavoc** [comment]
Could we implement SVGs for automatic scaling?

**Comment by sapierens** [comment]
Good idea. I'll try try to make some icons in SVG and see how it works, when I'll get some free time.

**Comment by sapierens** [comment]
Hey, can you test [this](https://gist.github.com/sapierens/32a10a3081a0247f5ace31f3ea5a96da) by making it a new stylish theme? It should be working good, but I just want to make sure it works on actual high-dpi hardware. Some icons have yet to be finalized, but they all should look good (apart from tab loading animation and probably pocket icon). There might be a couple disappearing icon bugs as I haven't finished some parts.
