### ISSUE TITLE
Refresh button seems to be broken

### ISSUE THREAD

**Issue by TomberWolf** [sapierens/firefox-edge#21]
I don't know if it's a common issue but for me the refresh button is broken.

![refreshbutton](https://user-images.githubusercontent.com/9993839/29446177-107260e2-83eb-11e7-852b-afa0ccb2d4f4.jpg)

**Comment by sapierens** [comment]
This is fixed with version 55 of Firefox. If it's still not working on Waterfox 55, then Waterfox hasn't yet merged the refresh button changes from Firefox.

**Comment by TomberWolf** [comment]
Is there's something I can do to fix it on my own for Waterfox?
