### ISSUE TITLE
Firefox57 does not support stylish

### ISSUE THREAD

**Issue by jarvsipipi** [sapierens/firefox-edge#23]
Try to use firefox57, found that the version does not support stylish
os :windows10 64bit
browser version:firefox57.0b3

**Comment by sapierens** [comment]
The style won't be updated for Firefox 57. At least not in the foreseeable future.

I wouldn't be able to get it to nearly as many people as I do now, without stylish.
And the new Firefox theme has changed so much that a more sane option would be to rewrite the style from ground up, and I don't currently have time for that.

Personally I'm quite excited for the new Firefox theme and I don't really feel the need to use Firefox Edge. At least until it will get boring.
