### ISSUE TITLE
It's not working with the new version of Stylish

### ISSUE THREAD

**Issue by SirHedge** [sapierens/firefox-edge#24]
Stylish just got updated on my Firefox today and the theme is not working with it since. Can't add it from the site too. 

Thanks for this awesome style in the meanwhile.

**Comment by sapierens** [comment]
The latest version of Stylish doesn't support Firefox's UI styling.

You'll have to get back to [Stylish 2.1.1](https://addons.mozilla.org/en-US/firefox/addon/stylish/versions/?page=1#version-2.1.1) to be able to use the style again.
However with Firefox 57, only the new version of Stylish will work.

**Comment by SirHedge** [comment]
Thanks, I was able to roll back to the older stylish, now it works again. Also disabled the automatic update to prevent to install the new one again. Any heads up for the future? Thanks.

**Comment by sapierens** [comment]
Well, with Firefox 57+, the only way to style the UI will be by creating/editing userChrome.css file.
That alone removes a user-friendly way of installing and distributing themes.
On top of that, Firefox 57 comes with a complete UI overhaul. The sane thing for this theme would be to create a full re-write, for what I unfortunately do not have time.

Personally, I'm looking forward to the new Firefox UI. I might do some small userChrome.css tweaks to it, if I'll find something that I don't like. But I don't see myself rewriting this theme for Firefox 57 in the near future.

**Comment by SirHedge** [comment]
Thanks for the really great explanation. I'm sad to hear this trough. I really like what you did with the browser because I presonally love the Edge's look but it doesnt work that well for me at the moment. 

I just checked how it will look (Firefox 57). Its better because I hate the original rounded ui of the Mozilla.
Thanks for your work.
