### ISSUE TITLE
Firefox 56 and new stylish

### ISSUE THREAD

**Issue by bishem** [sapierens/firefox-edge#27]
hello,

it seems that the the theme does not install at all with the new stylish plugin.
there is a confirmation box but then nothing.
i tried following the migration tutorial on stylish with no result.
its possible that the theme is not compatible with either the 56th version (or higher) of Firefox or maybe not adapted to the new stylish plugin (i see a bunch of errors in the CSS when i try the import from Mozilla option in the plugin's settings)

**Comment by usyboi** [comment]
@Cao-Lao web-extenstions dont support firefox theming they only way is that if he updates it to a userChrome.css file
