### ISSUE TITLE
Make the menu drop-down dark in the Dark version

### ISSUE THREAD

**Issue by HammyHavoc** [sapierens/firefox-edge#3]
Looks great aside from the menu drop-down being light rather than dark. DeepDark does this rather well in their theme.

**Comment by sapierens** [comment]
Initially I decided to not touch sub/context menu's to minimize any possibility of the theme breaking with a new version of Firefox. But I assume I could simply invert it like DeepDark does it. Have to figure out the file size constraint first.

**Comment by TheConsciousness** [comment]
Support this change as well. Thank you.
