### ISSUE TITLE
Breaks formatting on some websites

### ISSUE THREAD

**Issue by HammyHavoc** [sapierens/firefox-edge#4]
Formatting looks seriously broken here: [https://www.splitanatom.com/services/audio-production/scoring](https://www.splitanatom.com/services/audio-production/scoring
)
Compare with and without having the Stylish theme enabled. The spacing between the sections changes completely.

**Comment by sapierens** [comment]
For me it looks identical with and without the theme enabled, and close to identical with Chrome and Edge results. Can you double check and provide some screenshots?

**Comment by sapierens** [comment]
Any more information on this?

**Comment by sapierens** [comment]
Closing, due to lack of information and no other reports.
