### ISSUE TITLE
Issues on Linux Mint

### ISSUE THREAD

**Issue by feren** [sapierens/firefox-edge#5]
The close tab button, as well as the History Button on the Address Bar, are bugged, I'll show you what I mean:
![screenshot from 2016-12-01 14-11-39](https://cloud.githubusercontent.com/assets/11057934/20796838/17d4e388-b7d0-11e6-8b4a-eaebc0550792.png)
![screenshot from 2016-12-01 14-11-59](https://cloud.githubusercontent.com/assets/11057934/20796846/26bd3d0a-b7d0-11e6-98d4-896a454edad1.png)

Apart from that and the buttons sticking out on hover, working really well!

**Comment by feren** [comment]
...also, ignore the white patch, that's because of my GTK Theme...

**Comment by sapierens** [comment]
This is fixed in the next patch, but I still see other minor visual bugs. Looks like they occur because Firefox on Linux is using a slightly different base CSS for appearance than on Windows. So I don't think I can do much about other minor bugs.

**Comment by feren** [comment]
@sapierens Hmm, not seeing anything different on Firefox on Mint 18.1 BETA:
![screenshot from 2016-12-05 18-17-53](https://cloud.githubusercontent.com/assets/11057934/20896768/27a49822-bb17-11e6-93cf-5c4b4688d413.png)

**Comment by cinnamoner** [comment]
I'd like it on ... Linux.

**Comment by sapierens** [comment]
> @sapierens Hmm, not seeing anything different on Firefox on Mint 18.1 BETA:

The update is not out yet but it will be in the next couple of days. I still have to finish some other things.

**Comment by sapierens** [comment]
> I'd like it on ... Linux.

I'll take another look at it before this patch releases, but if some of the required changes will conflict with Firefox on Windows, I'll have to keep those fixes out.

**Comment by sapierens** [comment]
Looks like I actually managed to fix all the visual bugs (that I could spot) without interfering with Windows version of Firefox.

**Comment by cinnamoner** [comment]
> Looks like I actually managed to fix all the visual bugs (that I could spot) without interfering with Windows version of Firefox.

@sapierens
@feren 

Should I understand it now also works with Firefox on Linux?

**Comment by sapierens** [comment]
Yes, most of the visual bugs have been sorted for the Linux version. There are still a few on the bookmarks toolbar, but it's all minor stuff. The update with better Linux support is now live on userstyles.

**Comment by feren** [comment]
Fixed thanks!

**Comment by cinnamoner** [comment]
@sapierens Great job. Kinda like the minimalism of *Preject Spartan* which gave birth to *Edge*. As said, kinda like the UI in Edge. It's just the underlying code that I'm suspicious of. Therefore your Edge theme for Firefox is a great accomplishment. Thanks!
